# Generic settings used across our module.
generic_settings:
  # Allowed modes are instant scan and daemon_mode
  operation_mode: "daemon_mode"
  work_directory: "/tmp/atal"
  db_directory: "./database"
  db_filename: "atal.db"

# Scan configurations
scan_settings:
  target_directory: "/home/lakshy/Citadel/Library"
  # Allows only zip files. Pack your rules into a zip file.
  rules_filepath: "../rules.zip"

# Logging configuration
logging:
  enable_console: True
  use_json: True
  enable_file_logging: True
  log_directory: "./logs"
  log_filename: "atal.log"
  max_size_mb: 50
  max_age_days: 1
  max_backups: 5
  log_level: "info"
  time_format: "UNIXMS" # Zerolog timeformat